name: vpn_app
description: Simple VPN UI skeleton
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
